# Importing all necessary libraries

In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
import warnings
warnings.filterwarnings('ignore')
import tensorflow as tf
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense,Dropout
from tensorflow import keras
from tensorflow.keras.callbacks import EarlyStopping

# Reading the dataset

In [2]:
df=pd.read_csv('E-commerce_Shipping_Data.csv')
df

ID Warehouse_block Mode_of_Shipment  Customer_care_calls  \
0          1               D           Flight                    4   
1          2               F           Flight                    4   
2          3               A           Flight                    2   
3          4               B           Flight                    3   
4          5               C           Flight                    2   
...      ...             ...              ...                  ...   
10994  10995               A             Ship                    4   
10995  10996               B             Ship                    4   
10996  10997               C             Ship                    5   
10997  10998               F             Ship                    5   
10998  10999               D             Ship                    2   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                    2                  177                3   
1                    5                  216                2   
2                    2                  183                4   
3                    3                  176                4   
4                    2                  184                3   
...                ...                  ...              ...   
10994                1                  252                5   
10995                1                  232                5   
10996                4                  242                5   
10997                2                  223                6   
10998                5                  155                5   

      Product_importance Gender  Discount_offered  Weight_in_gms  \
0                    low      F                44           1233   
1                    low      M                59           3088   
2                    low      M                48           3374   
3                 medium      M                10           1177   
4                 medium      F                46           2484   
...                  ...    ...               ...            ...   
10994             medium      F                 1           1538   
10995             medium      F                 6           1247   
10996                low      F                 4           1155   
10997             medium      M                 2           1210   
10998                low      F                 6           1639   

       Reached.on.Time_Y.N  
0                        1  
1                        1  
2                        1  
3                        1  
4                        1  
...                    ...  
10994                    1  
10995                    0  
10996                    0  
10997                    0  
10998                    0  

[10999 rows x 12 columns]

# Checking for null values present in dataset

In [3]:
df.isnull().sum()

ID                     0
Warehouse_block        0
Mode_of_Shipment       0
Customer_care_calls    0
Customer_rating        0
Cost_of_the_Product    0
Prior_purchases        0
Product_importance     0
Gender                 0
Discount_offered       0
Weight_in_gms          0
Reached.on.Time_Y.N    0
dtype: int64

# As we can see there are no null values present in the dataset

# Checking for missing values in dataset

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10999 entries, 0 to 10998
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype 
---  ------               --------------  ----- 
 0   ID                   10999 non-null  int64 
 1   Warehouse_block      10999 non-null  object
 2   Mode_of_Shipment     10999 non-null  object
 3   Customer_care_calls  10999 non-null  int64 
 4   Customer_rating      10999 non-null  int64 
 5   Cost_of_the_Product  10999 non-null  int64 
 6   Prior_purchases      10999 non-null  int64 
 7   Product_importance   10999 non-null  object
 8   Gender               10999 non-null  object
 9   Discount_offered     10999 non-null  int64 
 10  Weight_in_gms        10999 non-null  int64 
 11  Reached.on.Time_Y.N  10999 non-null  int64 
dtypes: int64(8), object(4)
memory usage: 1.0+ MB


# As we can see here there are no missing values in the dataset

# Checking for descriptive statisitcs

In [5]:
df.describe()

ID  Customer_care_calls  Customer_rating  Cost_of_the_Product  \
count  10999.00000         10999.000000     10999.000000         10999.000000   
mean    5500.00000             4.054459         2.990545           210.196836   
std     3175.28214             1.141490         1.413603            48.063272   
min        1.00000             2.000000         1.000000            96.000000   
25%     2750.50000             3.000000         2.000000           169.000000   
50%     5500.00000             4.000000         3.000000           214.000000   
75%     8249.50000             5.000000         4.000000           251.000000   
max    10999.00000             7.000000         5.000000           310.000000   

       Prior_purchases  Discount_offered  Weight_in_gms  Reached.on.Time_Y.N  
count     10999.000000      10999.000000   10999.000000         10999.000000  
mean          3.567597         13.373216    3634.016729             0.596691  
std           1.522860         16.205527    1635.377251             0.490584  
min           2.000000          1.000000    1001.000000             0.000000  
25%           3.000000          4.000000    1839.500000             0.000000  
50%           3.000000          7.000000    4149.000000             1.000000  
75%           4.000000         10.000000    5050.000000             1.000000  
max          10.000000         65.000000    7846.000000             1.000000

# Descriptive statistics shows the mean and median values of the columns in dataset. This shows that all the columns have normal skewness except 2 columns which shows left and right skewness but does not affect the output categorical columns

# Converting the categorical data into numerical values

In [6]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder()
df[['Warehouse_block','Mode_of_Shipment','Product_importance','Gender']]=oe.fit_transform(df[['Warehouse_block','Mode_of_Shipment','Product_importance','Gender']])

In [7]:
df

ID  Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
0          1              3.0               0.0                    4   
1          2              4.0               0.0                    4   
2          3              0.0               0.0                    2   
3          4              1.0               0.0                    3   
4          5              2.0               0.0                    2   
...      ...              ...               ...                  ...   
10994  10995              0.0               2.0                    4   
10995  10996              1.0               2.0                    4   
10996  10997              2.0               2.0                    5   
10997  10998              4.0               2.0                    5   
10998  10999              3.0               2.0                    2   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                    2                  177                3   
1                    5                  216                2   
2                    2                  183                4   
3                    3                  176                4   
4                    2                  184                3   
...                ...                  ...              ...   
10994                1                  252                5   
10995                1                  232                5   
10996                4                  242                5   
10997                2                  223                6   
10998                5                  155                5   

       Product_importance  Gender  Discount_offered  Weight_in_gms  \
0                     1.0     0.0                44           1233   
1                     1.0     1.0                59           3088   
2                     1.0     1.0                48           3374   
3                     2.0     1.0                10           1177   
4                     2.0     0.0                46           2484   
...                   ...     ...               ...            ...   
10994                 2.0     0.0                 1           1538   
10995                 2.0     0.0                 6           1247   
10996                 1.0     0.0                 4           1155   
10997                 2.0     1.0                 2           1210   
10998                 1.0     0.0                 6           1639   

       Reached.on.Time_Y.N  
0                        1  
1                        1  
2                        1  
3                        1  
4                        1  
...                    ...  
10994                    1  
10995                    0  
10996                    0  
10997                    0  
10998                    0  

[10999 rows x 12 columns]

# As we can see all the categorical columns have been converted into their numerical form

# Checking the correlation between columns

In [8]:
df.corr().style.background_gradient()

# As we can see, only the column Discount_offered is affecting the output target column strongly

# Dropping Unecessary columns

In [9]:
df.drop(['ID'],axis=1,inplace=True)

In [10]:
df

Warehouse_block  Mode_of_Shipment  Customer_care_calls  \
0                  3.0               0.0                    4   
1                  4.0               0.0                    4   
2                  0.0               0.0                    2   
3                  1.0               0.0                    3   
4                  2.0               0.0                    2   
...                ...               ...                  ...   
10994              0.0               2.0                    4   
10995              1.0               2.0                    4   
10996              2.0               2.0                    5   
10997              4.0               2.0                    5   
10998              3.0               2.0                    2   

       Customer_rating  Cost_of_the_Product  Prior_purchases  \
0                    2                  177                3   
1                    5                  216                2   
2                    2                  183                4   
3                    3                  176                4   
4                    2                  184                3   
...                ...                  ...              ...   
10994                1                  252                5   
10995                1                  232                5   
10996                4                  242                5   
10997                2                  223                6   
10998                5                  155                5   

       Product_importance  Gender  Discount_offered  Weight_in_gms  \
0                     1.0     0.0                44           1233   
1                     1.0     1.0                59           3088   
2                     1.0     1.0                48           3374   
3                     2.0     1.0                10           1177   
4                     2.0     0.0                46           2484   
...                   ...     ...               ...            ...   
10994                 2.0     0.0                 1           1538   
10995                 2.0     0.0                 6           1247   
10996                 1.0     0.0                 4           1155   
10997                 2.0     1.0                 2           1210   
10998                 1.0     0.0                 6           1639   

       Reached.on.Time_Y.N  
0                        1  
1                        1  
2                        1  
3                        1  
4                        1  
...                    ...  
10994                    1  
10995                    0  
10996                    0  
10997                    0  
10998                    0  

[10999 rows x 11 columns]

# Splitting the dataset

In [11]:
x=df.iloc[:,0:-1].values
x

array([[3.000e+00, 0.000e+00, 4.000e+00, ..., 0.000e+00, 4.400e+01,
        1.233e+03],
       [4.000e+00, 0.000e+00, 4.000e+00, ..., 1.000e+00, 5.900e+01,
        3.088e+03],
       [0.000e+00, 0.000e+00, 2.000e+00, ..., 1.000e+00, 4.800e+01,
        3.374e+03],
       ...,
       [2.000e+00, 2.000e+00, 5.000e+00, ..., 0.000e+00, 4.000e+00,
        1.155e+03],
       [4.000e+00, 2.000e+00, 5.000e+00, ..., 1.000e+00, 2.000e+00,
        1.210e+03],
       [3.000e+00, 2.000e+00, 2.000e+00, ..., 0.000e+00, 6.000e+00,
        1.639e+03]])

In [12]:
y=df.iloc[:,-1].values
y

array([1, 1, 1, ..., 0, 0, 0], dtype=int64)

# Data Scaling

In [13]:
from sklearn.preprocessing import StandardScaler
sc=StandardScaler()
x=sc.fit_transform(x)

# Splitting the dataset into training and testing dataset

In [14]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest=train_test_split(x,y,test_size=0.3,random_state=0)

In [15]:
xtrain

array([[ 1.11803399,  0.63834175, -0.04771132, ..., -0.99176046,
        -0.57842252, -0.17306685],
       [ 1.11803399,  0.63834175, -0.92379938, ..., -0.99176046,
        -0.64013267,  0.96189107],
       [-1.56534517,  0.63834175, -0.92379938, ...,  1.00830799,
         2.38366454, -1.25176609],
       ...,
       [ 1.11803399, -0.68290796, -0.04771132, ...,  1.00830799,
        -0.64013267,  0.58459094],
       [ 1.11803399, -0.68290796, -0.04771132, ...,  1.00830799,
        -0.70184282, -1.16615504],
       [-1.56534517, -0.68290796, -0.04771132, ..., -0.99176046,
         0.22380939,  0.04952188]])

In [16]:
ytrain

array([1, 1, 1, ..., 0, 1, 1], dtype=int64)

In [17]:
xtest

array([[-1.56534517, -2.00415767,  0.82837675, ...,  1.00830799,
        -0.57842252,  0.49714537],
       [ 1.11803399, -2.00415767,  1.70446482, ..., -0.99176046,
        -0.70184282, -1.41136955],
       [ 1.11803399,  0.63834175, -1.79988745, ...,  1.00830799,
        -0.20816164, -0.13759942],
       ...,
       [ 1.11803399,  0.63834175, -0.92379938, ..., -0.99176046,
        -0.57842252,  0.49408783],
       [ 1.11803399, -0.68290796,  0.82837675, ..., -0.99176046,
        -0.51671238,  1.07868901],
       [-1.56534517,  0.63834175,  0.82837675, ...,  1.00830799,
        -0.57842252, -1.00532857]])

In [18]:
ytest

array([1, 0, 1, ..., 1, 1, 0], dtype=int64)

# Building the model

In [19]:
ann=Sequential()

# Adding the hidden and output Layers

In [30]:
ann.add(Dense(500,activation='relu'))
ann.add(Dropout(rate=0.3))
ann.add(Dense(300,activation='relu'))
ann.add(Dropout(rate=0.2))
ann.add(Dense(100,activation='relu'))
ann.add(Dropout(rate=0.1))
ann.add(Dense(1,activation='sigmoid'))

In [31]:
es=EarlyStopping(monitor='val_loss',patience=25,verbose=1,mode='min')

In [32]:
ann.compile(optimizer='adam',loss='binary_crossentropy',metrics=['accuracy'])

# Training the model

In [33]:
history=ann.fit(xtrain,ytrain,epochs=300,batch_size=100,validation_data=(xtest,ytest),callbacks=[es],verbose=1)

Epoch 1/300
77/77 [==============================] - 2s 7ms/step - loss: 0.5288 - accuracy: 0.6668 - val_loss: 0.5504 - val_accuracy: 0.6748
Epoch 2/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4797 - accuracy: 0.7101 - val_loss: 0.5657 - val_accuracy: 0.6706
Epoch 3/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4762 - accuracy: 0.7207 - val_loss: 0.5833 - val_accuracy: 0.6624
Epoch 4/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4684 - accuracy: 0.7253 - val_loss: 0.5448 - val_accuracy: 0.6733
Epoch 5/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4683 - accuracy: 0.7254 - val_loss: 0.5851 - val_accuracy: 0.6597
Epoch 6/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4636 - accuracy: 0.7317 - val_loss: 0.5742 - val_accuracy: 0.6764
Epoch 7/300
77/77 [==============================] - 0s 5ms/step - loss: 0.4608 - accuracy: 0.7346 - val_loss: 0.5611 - val_accuracy: 0.6715
Epoch 8/300
7

# Making predictions

In [34]:
ypred=ann.predict(xtest)

104/104 [==============================] - 0s 884us/step


In [35]:
ypred=np.where(ypred>0.5,1,0)
ypred

array([[1],
       [1],
       [1],
       ...,
       [0],
       [0],
       [1]])

# Checking Accuracy

In [36]:
from sklearn.metrics import classification_report
print(classification_report(ytest,ypred))

              precision    recall  f1-score   support

           0       0.58      0.66      0.62      1379
           1       0.73      0.65      0.69      1921

    accuracy                           0.65      3300
   macro avg       0.65      0.66      0.65      3300
weighted avg       0.66      0.65      0.66      3300



# Accuracy of our model is 65%